### ISSUE TITLE
Include code for videos 26-31

### ISSUE THREAD

**Issue by connecteev** [WatheqAlshowaiter/bookings-codecourse#1]
Include code for videos 26-31 corresponding to the course https://codecourse.com/courses/build-a-booking-system-with-livewire

**Comment by WatheqAlshowaiter** [comment]
@connecteev 

done!

thanks for reminding me about that.

**Comment by connecteev** [comment]
@WatheqAlshowaiter thanks for doing that! 

ps. also have a question for you, I will send you an email.
